spring:
  data:
    mongodb:
      port: 27017
      host: localhost
      database: book


  mongo-db:
    write-concern:
      journal: false
    read-concern: local



logging:
  level:
    ROOT: ERROR