spring:
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: never

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

  sql:
    init:
      schema-locations: schema.sql
      data-locations: data.sql
      mode: always

    properties:
      hibernate:
        format_sql: true

    show-sql: true


logging:
  level:
    ROOT: ERROR
