spring:
  batch:
    job:
      enabled: true
  shell:
    interactive:
      enabled: false

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    initialization-mode: always

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true

  h2:
    console:
    enabled: true
    path: /h2-console

  data:
    mongodb:
      host: localhost
      port: 27017
      database: SpringBatchExampleDB

logging:
  level:
    ROOT: ERROR